# Tasks to be executed when the workspace is started
tasks:
  - name: Install Kind
    init: |
      curl -Lo /tmp/kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
      chmod +x /tmp/kind
      sudo mv /tmp/kind /usr/local/bin/kind
    command: kind version
  - name: Install kubectl
    init: |
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      alias k=kubectl
    command: kubectl version --client
# Ports to expose (if needed)
